turbine.instanceUrlSuffix: :8080/hystrix.stream
turbine.aggregator.clusterConfig: coolstore
turbine.aggregator.clusters.coolstore: coolstore-cart.cart-service,coolstore-catalog.catalog-service,coolstore-inventory.inventory-service,coolstore-gateway.coolstore-gateway