---

##########################################################################
# springboot micro-services demo with Mongo on Gluster, Jaeger and Hystrix
##########################################################################

- name: Create an springbootdemo in development
  action: command oc login -u dev1 -p dev1
  tags: example1

- name: Create springbootdemo project
  action: command oc new-project {{springbootdemo}}
  tags: example1

- name: Create a springbootdemo application in development
  action: command oc new-app --template=1-springboot-mongo-gluster
  tags: example1

- name: Copy Config Map File
  copy: src="application.yaml" dest="."
  tags: example1

- name: Create turbine server config map
  action: command oc create configmap turbine-server --from-file=application.yml -n {{springbootdemo}}
  tags:example1

- name: Create a hystrix-dashboard
  action: command oc create -f http://repo1.maven.org/maven2/io/fabric8/kubeflix/hystrix-dashboard/1.0.28/hystrix-dashboard-1.0.28-openshift.yml
  tags: example1

- name: Expose the hystrix-dashboard
  action: command oc expose service hystrix-dashboard --port=8080
  tags: example1

- name: Create and exposet a jaeger-dashboard
  shell: 'oc process -f https://raw.githubusercontent.com/jaegertracing/jaeger-openshift/master/all-in-one/jaeger-all-in-one-template.yml | oc create -f -'
  tags: example1



