apiVersion: v1
kind: BuildConfig
metadata:
  name: devpipeline
  labels:
    name: devpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "nodejs-offline-example", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage 'build'\nopenshiftBuild(buildConfig: 'nodejs-offline-example', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'nodejs-offline-example')\nopenshiftScale(deploymentConfig: 'nodejs-offline-example',replicaCount: '2')\n}"
  output:
  resources:
  postCommit:
